apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: contact-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/civicpulse/contact-api.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: civpulse-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
